permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author: 
  name: LeeWong
  email: wangli_100000@163.com
  link: http://leewongsnail.github.io/
  weibo: 
  github: https://github.com/LeeWongSnail

# 站点信息
title: 魏景云的博客 
description: 魏景云的博客
url: http://weijingyunios.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://img.hoop8.com/attachments/1602/8561790581128.jpg
favicon: http://img.hoop8.com/attachments/1602/8561790581128.jpg

# google analytics 设置
ga:
  id: 
  url: https://github.com/LeeWongSnail

# disqus 设置
disqus:
  shortname: LeeWong
